INSERT INTO [BpPROMOSER].[dbo].[MixAna] (
    [ItemType],
    [ItemUse],
    [ItemHide],
    [RecCreate],
    [RecChange],
    [RecLocked],
    [CatCod],--[RAGCLI],
    [ItemID],--[CODCLI],
    [ItemDes],--[RAGSOC],+[RAGSOC1],
    [Ind],--[INDIR],
    [Cap],--[CAP],
    [Loc],--[LOCAL],
    [Pro],--[PROV],
    [ItemMemo],--[INDIRA],
    [Info2],--[CAPA],
    [Info3],--[LOCALA],
    [Info4],--[PROVA],
    [CFis],--[CODFISC],
    [PIva],--[PARTIVA],
    [PagCod],--[CODPAG],
    [IvaCod],--[IVA],
    [AgeCod],--[CODAGE],
    [Info9],--[ADDSPESE],
    [Info5],--[TEL],
    [Info6],--[TEL2],
    [Info7],--[FAX],
    [ItemInfo],--[EMAIL],
    [Info8],--[RESPRAP],
    [TrPorto],--[CODPOR],
    [Tab1],--[CODTRA],
    [VetCod]--[CODVET]
    )
SELECT
'1',
'20',
'0',
'2024-11-25',
'2024-11-25',
'0',
LTRIM(RTRIM([RAGCLI])),--[CatCod],
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LTRIM(RTRIM([CODCLI])),' ',''),'&','-N-'),'''','-'),'.',''),'+','P'),--[ItemID],
CONCAT(LTRIM(RTRIM([RAGSOC])),' ',LTRIM(RTRIM([RAGSOC1]))),--[ItemDes],
LTRIM(RTRIM([INDIR])),--[Ind],
LTRIM(RTRIM([CAP])),--[Cap],
LTRIM(RTRIM([LOCAL])),--[Loc],
LTRIM(RTRIM([PROV])),--[Pro],
LTRIM(RTRIM([INDIRA])),--[ItemMemo],
LTRIM(RTRIM([CAPA])),--[Info2],
LTRIM(RTRIM([LOCALA])),--[Info3],
LTRIM(RTRIM([PROVA])),--[Info4],
LTRIM(RTRIM([CODFISC])),--[CFis],
LTRIM(RTRIM([PARTIVA])),--[PIva],
CASE WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('AC','BONA','PAA') THEN 'BB14'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('BO01') THEN 'BB03'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('BO02') THEN 'BB02'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('BO03') THEN 'BB12'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('BO04') THEN 'BB05'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('BO06','BON','BANC') THEN 'BB01'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('BO30') THEN 'BB09'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('BO45') THEN 'BB13'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('COB1') THEN 'BB15'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('COB3') THEN 'BB16'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('CONT') THEN 'RD01'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('CORB') THEN 'BB17'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('PKS2') THEN 'ASS01'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('PKS3') THEN 'CARCR01'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB01') THEN 'RB12'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB04') THEN 'RB15'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB05') THEN 'RB16'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB21') THEN 'RB01'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB22') THEN 'RB02'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB23') THEN 'RB03'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB25') THEN 'RB05'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB26') THEN 'RB06'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB28') THEN 'RB08'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RB40') THEN 'RB17'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RD01','PAG1') THEN 'RD03'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RD02') THEN 'RD14'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RD03') THEN 'RD04'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RD06') THEN 'RD07'
WHEN UPPER(LTRIM(RTRIM([CODPAG]))) IN ('RD12') THEN 'RD15'
ELSE NULL END,--[PagCod],
CASE WHEN UPPER(LTRIM(RTRIM([IVA]))) IN ('20','21','22','41','42') THEN '01'
WHEN UPPER(LTRIM(RTRIM([IVA]))) IN ('4') THEN '03'
ELSE NULL END,--[IvaCod],
LTRIM(RTRIM([CODAGE])),--[AgeCod],
LTRIM(RTRIM([ADDSPESE])),--[Info9],
LTRIM(RTRIM([TEL])),--[Info5],
LTRIM(RTRIM([TEL2])),--[Info6],
LTRIM(RTRIM([FAX])),--[Info7],
LTRIM(RTRIM([EMAIL])),--[ItemInfo],
LTRIM(RTRIM([RESPRAP])),--[Info8],
CASE WHEN UPPER(LTRIM(RTRIM([CODPOR]))) IN ('1','2','3') THEN '1'
WHEN UPPER(LTRIM(RTRIM([CODPOR]))) IN ('5','10') THEN '2'
WHEN UPPER(LTRIM(RTRIM([CODPOR]))) IN ('4','7') THEN '3'
ELSE NULL END,--[TrPorto],
LTRIM(RTRIM([CODTRA])),--[Tab1],
LTRIM(RTRIM([CODVET]))--[VetCod]
FROM [BpPROMOSER].[dbo].[tempClienti]