CREATE TABLE [tempClienti]( 
    [id] INT IDENTITY(1,1) 
    ,[RAGCLI] nvarchar(512) NULL
	,[CODCLI] nvarchar(512) NULL
	,[RAGSOC] nvarchar(512) NULL
	,[RAGSOC1] nvarchar(512) NULL
	,[INDIR] nvarchar(512) NULL
	,[CAP] nvarchar(512) NULL
	,[LOCAL] nvarchar(512) NULL
	,[PROV] nvarchar(512) NULL
	,[INDIRA] nvarchar(512) NULL
	,[CAPA] nvarchar(512) NULL
	,[LOCALA] nvarchar(512) NULL
	,[PROVA] nvarchar(512) NULL
	,[CODFISC] nvarchar(512) NULL
	,[PARTIVA] nvarchar(512) NULL
	,[CODPAG] nvarchar(512) NULL
	,[IVA] nvarchar(512) NULL
	,[CODAGE] nvarchar(512) NULL
	,[ADDSPESE] nvarchar(512) NULL
	,[TEL] nvarchar(512) NULL
	,[TEL2] nvarchar(512) NULL
	,[FAX] nvarchar(512) NULL
	,[EMAIL] nvarchar(512) NULL
	,[RESPRAP] nvarchar(512) NULL
	,[CODPOR] nvarchar(512) NULL
	,[CODTRA] nvarchar(512) NULL
	,[CODVET] nvarchar(512) NULL
	)