USE [BpDataSystem]

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 201, NULL, NULL, N'K1', N'AnaCod', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, 2, N'ShowQT MixAnaCli', N'ShowCM "LinkCliCod"', N'Cliente collegato', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 53, NULL, NULL, NULL, N'billing_address_1', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione indirizzo', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 54, NULL, NULL, NULL, N'billing_address_2', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione indirizzo 2', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 55, NULL, NULL, NULL, N'billing_city', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione località', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 52, NULL, NULL, NULL, N'billing_company', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione azienda', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 58, NULL, NULL, NULL, N'billing_country', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione nazione', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 59, NULL, NULL, NULL, N'billing_email', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione email', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 50, NULL, NULL, NULL, N'billing_first_name', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione nome', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 51, NULL, NULL, NULL, N'billing_last_name', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione cognome', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 60, NULL, NULL, NULL, N'billing_phone', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione telefono', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 57, NULL, NULL, NULL, N'billing_postcode', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione CAP', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 56, NULL, NULL, NULL, N'billing_state', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Fatturazione provincia', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 5, NULL, NULL, NULL, N'cart_hash', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Hash carrello', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 35, NULL, NULL, NULL, N'cart_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA merce', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 76, NULL, NULL, NULL, N'coupon_code', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Codice coupon', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 77, NULL, NULL, NULL, N'coupon_discount', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Sconto coupon', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 78, NULL, NULL, NULL, N'coupon_discount_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA coupon', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 79, NULL, NULL, NULL, N'coupon_discount_type', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Tipo coupon', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 81, NULL, NULL, NULL, N'coupon_free_shipping', N'bit', N'boolean01', 1, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Coupon spedizione gratuita', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 80, NULL, NULL, NULL, N'coupon_nominal_amount', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Valore nominale coupon', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 98, NULL, NULL, NULL, N'created_via', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Creato attraverso', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 24, NULL, NULL, NULL, N'currency', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Divisa', NULL, N'PRO | GAG | ADU | Divisa', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 11, NULL, NULL, NULL, N'customer_email', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Email cliente', NULL, N'         | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 12, NULL, NULL, NULL, N'customer_first_name', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Nome cliente', NULL, N'         | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 10, NULL, NULL, NULL, N'customer_id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID cliente', NULL, N'PRO | GAG | ADU | AnaCodFrom', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 16, NULL, NULL, NULL, N'customer_ip_address', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IP cliente', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 13, NULL, NULL, NULL, N'customer_last_name', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Cognome cliente', NULL, N'         | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 15, NULL, NULL, NULL, N'customer_note', N'varchar(MAX)', N'text', 0, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Note cliente', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 14, NULL, NULL, NULL, N'customer_role', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Ruolo cliente', NULL, N'         | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 17, NULL, NULL, NULL, N'customer_user_agent', N'varchar(256)', N'text', 256, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'UA cliente', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 104, NULL, NULL, NULL, N'date_completed', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data completamento', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 105, NULL, NULL, NULL, N'date_completed_gmt', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data completamento', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 100, NULL, NULL, NULL, N'date_created', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data creazione', NULL, N'PRO | GAG | ADU | RecCreate', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 101, NULL, NULL, NULL, N'date_created_gmt', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data creazione', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 102, NULL, NULL, NULL, N'date_modified', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data modifica', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 103, NULL, NULL, NULL, N'date_modified_gmt', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data modifica', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 106, NULL, NULL, NULL, N'date_paid', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data pagamento', NULL, N'PRO |           | ADU | PagStart', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 107, NULL, NULL, NULL, N'date_paid_gmt', N'datetime', N'datetime', 19, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Data pagamento', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 36, NULL, NULL, NULL, N'discount_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA sconto', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 32, NULL, NULL, NULL, N'discount_total', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Totale sconto', NULL, N'PRO | GAG | ADU | DocSconti', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 72, NULL, NULL, NULL, N'fee_name', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Descrizione express', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 73, NULL, NULL, NULL, N'fee_tax_class', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Classe IVA express', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 74, NULL, NULL, NULL, N'fee_total', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Totale express', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 75, NULL, NULL, NULL, N'fee_total_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Totale IVA express', NULL, N'PRO |           |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 2, N'U1', NULL, NULL, N'id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID ordine', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 99, NULL, NULL, NULL, N'is_editable', N'bit', N'boolean01', 1, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Modificabile', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 18, NULL, NULL, NULL, N'link_customer', N'varchar(256)', N'text', 256, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'URL cliente', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 9, NULL, NULL, NULL, N'link_self', N'varchar(256)', N'text', 256, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'URL ordine', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 20, NULL, NULL, NULL, N'needs_payment', N'bit', N'boolean01', 1, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Da pagare', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 21, NULL, NULL, NULL, N'needs_processing', N'bit', N'boolean01', 1, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Da processare', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 3, NULL, NULL, NULL, N'number', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Numero ordine', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 4, NULL, NULL, NULL, N'order_key', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Chiave ordine', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 1, N'U1', NULL, NULL, N'origin', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Origine', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 6, NULL, NULL, NULL, N'parent_id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID genitore', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 22, NULL, NULL, NULL, N'payment_method', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Metodo di pagamento', NULL, N'PRO | GAG | ADU | PagCod', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 23, NULL, NULL, NULL, N'payment_method_title', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Descrizione metodo di pagamento', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 26, NULL, NULL, NULL, N'payment_url', N'varchar(256)', N'text', 256, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'URL pagamento', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 39, NULL, NULL, NULL, N'prices_include_tax', N'bit', N'boolean01', 1, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA inclusa nel totale', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 64, NULL, NULL, NULL, N'shipping_address_1', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione indirizzo', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 65, NULL, NULL, NULL, N'shipping_address_2', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione indirizzo 2', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 66, NULL, NULL, NULL, N'shipping_city', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione località', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 63, NULL, NULL, NULL, N'shipping_company', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione azienda', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 69, NULL, NULL, NULL, N'shipping_country', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione nazione', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 61, NULL, NULL, NULL, N'shipping_first_name', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione nome', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 62, NULL, NULL, NULL, N'shipping_last_name', N'nvarchar(32)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione cognome', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 71, NULL, NULL, NULL, N'shipping_method_title', N'varchar(128)', N'text', 128, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione descrizione', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 70, NULL, NULL, NULL, N'shipping_phone', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione telefono', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 68, NULL, NULL, NULL, N'shipping_postcode', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione CAP', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 67, NULL, NULL, NULL, N'shipping_state', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Spedizione provincia', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 37, NULL, NULL, NULL, N'shipping_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA spedizione', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 33, NULL, NULL, NULL, N'shipping_total', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Totale spedizione', NULL, N'PRO | GAG | ADU | SpImballo', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 7, NULL, NULL, NULL, N'status', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Stato', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 31, NULL, NULL, NULL, N'subtotal', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Totale merce', NULL, N'         | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 44, NULL, NULL, NULL, N'tax_compound', N'bit', N'boolean01', 1, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA composta', NULL, N'PRO | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 40, NULL, NULL, NULL, N'tax_id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID IVA', NULL, N'PRO | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 43, NULL, NULL, NULL, N'tax_label', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Descrizione IVA', NULL, N'PRO | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 41, NULL, NULL, NULL, N'tax_rate_code', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Codice rata IVA', NULL, N'PRO | GAG |          | DocIvaCod', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 42, NULL, NULL, NULL, N'tax_rate_id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID rata IVA', NULL, N'PRO | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 46, NULL, NULL, NULL, N'tax_rate_percent', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Rata IVA', NULL, N'PRO |           |         |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 45, NULL, NULL, NULL, N'tax_tax_total', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA merce', NULL, N'PRO | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 30, NULL, NULL, NULL, N'total', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Totale', NULL, N'PRO | GAG | ADU | DocTot', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 49, NULL, NULL, NULL, N'total_line_items_quantity', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Quantità merce totale', NULL, N'         | GAG |          |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 34, NULL, NULL, NULL, N'total_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA totale', NULL, N'PRO | GAG | ADU | DocIva', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 25, NULL, NULL, NULL, N'transaction_id', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID transazione', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 200, N'', NULL, N'K2', N'Uniq', N'int', N'number', 10, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Documento collegato', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdImp_Pers', 8, NULL, NULL, NULL, N'version', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Versione', NULL, N'PRO |           | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 2, N'U1', NULL, NULL, N'id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID ordine', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 3, N'U1', NULL, NULL, N'id_lin', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID riga', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 16, NULL, NULL, NULL, N'link_image', N'varchar(256)', N'text', 256, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Immagine', NULL, N'PRO |          | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 7, NULL, NULL, NULL, N'name', N'varchar(256)', N'text', 256, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Descrizione variante', NULL, N'PRO |          | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 1, N'U1', NULL, NULL, N'origin', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Origine', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 5, NULL, NULL, NULL, N'parent_name', N'varchar(128)', N'text', 128, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Descrizione prodotto', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 202, NULL, NULL, N'K2', N'PrdCod', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, 2, N'If AppInfoGet("2015") = "1" Then
	ShowQT (MixAnaPrdAlias)
Else
	ShowQT (PrdAna)
EndIf', N'ShowCM "LinkPrdCod"', N'Prodotto collegato', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 9, NULL, NULL, NULL, N'price', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Prezzo', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 4, NULL, NULL, NULL, N'product_id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID prodotto', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 10, NULL, NULL, NULL, N'quantity', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Quantità', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 8, NULL, NULL, NULL, N'sku', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'SKU', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 11, NULL, NULL, NULL, N'subtotal', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Sottototale', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 14, NULL, NULL, NULL, N'subtotal_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA sottototale', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 13, NULL, NULL, NULL, N'tax_class', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Classe IVA', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 12, NULL, NULL, NULL, N'total', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Totale', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 15, NULL, NULL, NULL, N'total_tax', N'decimal(9, 3)', N'number3', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'IVA totale', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 201, N'', NULL, N'K3', N'Uniq', N'int', N'number', 10, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Riga collegata', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 200, N'', NULL, N'K1', N'UniqDoc', N'int', N'number', 10, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Documento collegato', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinImp_Pers', 6, NULL, NULL, NULL, N'variation_id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID variante', NULL, N'PRO |          | ADU |', NULL, NULL)
INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 6, NULL, NULL, NULL, N'display_key', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Descrizione parametro', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 8, NULL, NULL, NULL, N'display_value', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Testo parametro', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 2, N'U1', NULL, NULL, N'id', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID ordine', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 3, N'U1', NULL, NULL, N'id_lin', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID riga', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 4, N'U1', NULL, NULL, N'id_par', N'int', N'number', 9, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'ID parametro', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 5, NULL, NULL, NULL, N'key_', N'varchar(32)', N'text', 32, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Chiave parametro', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 1, N'U1', NULL, NULL, N'origin', N'varchar(16)', N'text', 16, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Origine', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 202, N'', NULL, N'K3', N'ParID', N'smallint', N'number', 2, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Parametro collegato', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 200, NULL, NULL, N'K1', N'UniqDoc', N'int', N'number', 10, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Documento collegato', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 201, N'', NULL, N'K2', N'UniqLin', N'int', N'number', 10, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Riga collegata', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImp_Pers', 7, NULL, NULL, NULL, N'value', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'Valore parametro', NULL, N'PRO | GAG | ADU |', NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImpSettings_Pers', 1, N'U1', NULL, NULL, N'id', N'varchar(64)', N'text', 64, 1, 1, 0, NULL, 200, NULL, 0, NULL, NULL, NULL, N'Slug', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImpSettings_Pers', 3, NULL, NULL, NULL, N'ParDes', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, 120, NULL, 0, NULL, NULL, NULL, N'Descrizione parametro', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImpSettings_Pers', 4, NULL, NULL, NULL, N'ParID', N'smallint', N'number', 4, 1, 1, 1, NULL, 60, NULL, 0, NULL, NULL, NULL, N'Indice parametro', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImpSettings_Pers', 5, NULL, NULL, NULL, N'ParLin', N'smallint', N'number', 4, 1, 1, 1, NULL, 60, NULL, 0, NULL, NULL, NULL, N'Posizione parametro', NULL, NULL, NULL, NULL)

INSERT [dbo].[SystemTableFields] ([TbName], [FieldOrdinal], [FieldIndex], [FieldIndexOrdinal], [FieldIndex1], [FieldName], [FieldDataType], [FieldEditType], [FieldChars], [FieldVisible], [FieldAllowEdit], [FieldAllowEmpty], [FieldTotal], [FieldWidth], [FieldDefault], [FieldZeroShow], [FieldQtShow], [FieldQtScript], [FieldLinkScript], [FieldCaption], [FieldHelp], [FieldInfo], [IsCustom], [Soft]) VALUES (N'CliOrdLinParImpSettings_Pers', 2, N'', NULL, NULL, N'TabCod', N'varchar(64)', N'text', 64, 1, 1, 1, NULL, 80, NULL, 0, 1, N'ShowQT (PrdFormTab)', NULL, N'Tabella associata', NULL, NULL, NULL, NULL)