INSERT INTO [BpSpit].[dbo].[tempProdotti] 
([Codice],[Descrizione]) 
SELECT * FROM (VALUES
('1','Edilizia&Architettura'),
('2','Contenimento energetico'),
('3','Sicurezza cantieri'),
('4','Acustica'),
('5','Due Diligence'),
('6','Strutture'),
('7','Consulenza Antincendio'),
('8','Consulenza Antiesplosione'),
('9','Consulenza Sicurezza funzionale'),
('10','Consulenza Direttiva Macchine'),
('11','Consulenza Direttiva Seveso'),
('12','Impianti Antincendio'),
('13','Impianti Elettrici'),
('14','Impianti Fotovoltaici'),
('15','Impianti Meccanici'),
('16','Docenze'),
('17','Condomini'),
('20','Formazione (ricevuta)'),
('21','Coordinamento ufficio'),
('22','Contabilita'' e amministrazione'),
('23','Attivita'' commerciale'),
('1.1','Verifica di conformita'' urbanistica/edilizia'),
('1.2','Verifiche di fattibilita'''),
('1.3','Progetto architettonico'),
('1.4','Pratiche catastali'),
('1.5','Rilievi laser scanner'),
('1.6','Rilievi con drone'),
('1.7','Rilievo topografico'),
('1.8','autorizzazioni ambientali'),
('1.9','da definire'),
('1.10','da definire'),
('1.11','da definire'),
('1.12','da definire'),
('1.13','da definire'),
('1.14','da definire'),
('1.15','da definire'),
('1.16','da definire'),
('1.17','da definire'),
('1.18','da definire'),
('1.19','da definire'),
('1.20','da definire'),
('1.21','consulenze'),
('2.1','Redazione Legge 10'),
('2.2','Modellazione energetica'),
('2.3','Rilevazione sistema edificio-impianto'),
('2.4','Attestato Prestazione Energetica (APE)'),
('2.5','Detrazioni fiscali'),
('2.6','Diagnosi energetica'),
('2.7','consulenze'),
('3.1','Coordinatore della Sicurezza in fase di Progettazione (CSP)'),
('3.2','Coordinatore della Sicurezza in fase di Esecuzione (CSE)'),
('3.3','Piano Operativo di Emergenza (POS)'),
('3.4','Linea Vita'),
('3.5','Pimus - Ponteggi'),
('4.1','Valutazione dei requisiti acustici passivi'),
('4.2','Clima acustico'),
('4.3','Impatto acustico'),
('4.4','consulenze'),
('5.1','Report impianti-ambiente'),
('5.2','Report manutentivo'),
('5.3','Monitoring'),
('6.1','sanatoria'),
('6.2','nuova costruzione'),
('6.3','ristrutturazione'),
('6.4','detrazioni fiscali'),
('6.5','resistenza al fuoco'),
('6.6','resistenza a esplosione'),
('6.7','consulenze'),
('7.1','Valutazione progetto'),
('7.2','Segnalazione Certificata di Inizio Attivita'' (SCIA)'),
('7.3','Rinnovo periodico di conforita'' antincendio'),
('7.4','Rinnovo e verifica funzionamento idranti'),
('7.5','FSE-S2 Resistenza al fuoco/Temperatura'),
('7.6','FSE-S2 Resistenza al fuoco/Val.strutturale'),
('7.7','FSE-S2 Resistenza al fuoco/Temperatura+Val.strutturale'),
('7.8','FSE-S3 Compartimentazione/Temperatura'),
('7.9','FSE-S3 Compartimentazione/Val.strutturale'),
('7.10','FSE-S3 Compartimentazione/Temperatura+Val.strutturale'),
('7.11','FSE-S4 Esodo'),
('7.12','FSE-S8 Gestione fumi'),
('7.13','FSE-Simulazioni esodo'),
('7.14','consulenze'),
('7.15','Valutazione Rischio Incendio (VRI)'),
('7.16','Piano emergenza'),
('7.17','Cert. REI'),
('7.18','Cert. IMP.'),
('7.19','Dich. PROD.'),
('7.20','Dich. IMP.'),
('8.1','Documento Protezione Contro le Eslosioni (DPCE)'),
('8.2','Zonizzazione'),
('8.3','Certificazione macchine'),
('8.4','consulenze'),
('9.1','Analisi Hazop'),
('9.2','Fault tree analysis'),
('9.3','Analisi Layer Of Protection Analysis (LOPA)'),
('9.4','Analisi Safety Integrity Level (SIL)'),
('12.1','Sprinkler'),
('12.2','Schiuma'),
('12.3','Gas'),
('12.4','Rilevazione'),
('12.5','Water mist bassa pressione'),
('12.6','Water mist alta pressione'),
('12.7','Idranti'),
('12.8','Sistemi di Evacuazione Forzata Fumo e Calore (SEFFC)'),
('12.9','Sistemi di Evacuazione Naturale Fumo e Calore (SENFC)'),
('12.10','Aerosol'),
('12.11','Staffaggi antisismici'),
('12.12','consulenze'),
('13.1','Distribuzione'),
('13.2','Speciali'),
('13.3','Domotica'),
('13.4','consulenze'),
('14.1','0-6kWp'),
('14.2','6-20kWp'),
('14.3','20-50kWp'),
('14.4','50-100kWp'),
('14.5','100kWp<P<500kWp'),
('14.6','500kWp<P<1000kWp'),
('14.7','>1000kWp'),
('14.8','Pratiche di connessione'),
('14.9','Dogane'),
('14.11','Adempimenti fiscali a cadenza annuale'),
('14.10','consulenze'),
('15.1','Termico'),
('15.2','Climatizzazione'),
('15.3','Ventilazione meccanica controllata'),
('15.4','Idrico-sanitario'),
('15.5','Trattamento aria'),
('15.6','Scarichi'),
('15.7','Adduzione Gas'),
('15.8','consulenze'),
('16.1','Formazione aziendale'),
('16.2','Corsi'),
('17.1','Verifica funzionalita'' impianto di TERRA - SRP'),
('17.2','Verifica funzionalita'' chiusura motorizzata - CANC'),
('17.3','Analisi acqua'),
('17.4','Rinnovo CPI'),
('17.5','Rinnovo CPI+verifica funzionamento idranti'),
('17.6','da definire'),
('X.X.1','Studio di fattibilita'''),
('X.X.2','Preliminare'),
('X.X.3','progetto definitivo/esecutivo'),
('X.X.4','BIM'),
('X.X.5','DL'),
('X.X.6','As built'),
('X.X.7','Collaudo'),
('X.X.8','Verifiche'),
('X.X.9','Dichiarazioni di Rispondenza'),
('X.X.10','CFD'),
('X.X.11','FEM')
) x([Codice],[Descrizione]);